//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.18 at 05:23:45 PM JST 
//


package net.tiger.star.nsen.jaxb;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}category"/>
 *         &lt;element ref="{}game_key"/>
 *         &lt;element ref="{}game_time"/>
 *         &lt;element ref="{}force_nicowari_off"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "category",
    "gameKey",
    "gameTime",
    "forceNicowariOff"
})
@XmlRootElement(name = "marquee")
public class Marquee {

    @XmlElement(required = true)
    protected Category category;
    @XmlElement(name = "game_key", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String gameKey;
    @XmlElement(name = "game_time", required = true)
    protected BigInteger gameTime;
    @XmlElement(name = "force_nicowari_off", required = true)
    protected BigInteger forceNicowariOff;

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link Category }
     *     
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link Category }
     *     
     */
    public void setCategory(Category value) {
        this.category = value;
    }

    /**
     * Gets the value of the gameKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGameKey() {
        return gameKey;
    }

    /**
     * Sets the value of the gameKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGameKey(String value) {
        this.gameKey = value;
    }

    /**
     * Gets the value of the gameTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGameTime() {
        return gameTime;
    }

    /**
     * Sets the value of the gameTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGameTime(BigInteger value) {
        this.gameTime = value;
    }

    /**
     * Gets the value of the forceNicowariOff property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getForceNicowariOff() {
        return forceNicowariOff;
    }

    /**
     * Sets the value of the forceNicowariOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setForceNicowariOff(BigInteger value) {
        this.forceNicowariOff = value;
    }

}
