//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.18 at 05:23:45 PM JST 
//


package net.tiger.star.nsen.jaxb;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}is_ns_stream"/>
 *         &lt;element ref="{}nstype"/>
 *         &lt;element ref="{}nspanel"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isNsStream",
    "nstype",
    "nspanel"
})
@XmlRootElement(name = "ns")
public class Ns {

    @XmlElement(name = "is_ns_stream", required = true)
    protected BigInteger isNsStream;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String nstype;
    @XmlElement(required = true)
    protected String nspanel;

    /**
     * Gets the value of the isNsStream property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIsNsStream() {
        return isNsStream;
    }

    /**
     * Sets the value of the isNsStream property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIsNsStream(BigInteger value) {
        this.isNsStream = value;
    }

    /**
     * Gets the value of the nstype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNstype() {
        return nstype;
    }

    /**
     * Sets the value of the nstype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNstype(String value) {
        this.nstype = value;
    }

    /**
     * Gets the value of the nspanel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNspanel() {
        return nspanel;
    }

    /**
     * Sets the value of the nspanel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNspanel(String value) {
        this.nspanel = value;
    }

}
