//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.18 at 05:23:45 PM JST 
//


package net.tiger.star.nsen.jaxb;

import java.math.BigInteger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NgScoring_QNAME = new QName("", "ng_scoring");
    private final static QName _UserPrefecture_QNAME = new QName("", "userPrefecture");
    private final static QName _BourbonUrl_QNAME = new QName("", "bourbon_url");
    private final static QName _IsVip_QNAME = new QName("", "is_vip");
    private final static QName _DisplayTime_QNAME = new QName("", "display_time");
    private final static QName _Enable_QNAME = new QName("", "enable");
    private final static QName _GameKey_QNAME = new QName("", "game_key");
    private final static QName _Addr_QNAME = new QName("", "addr");
    private final static QName _VipModeCount_QNAME = new QName("", "vip_mode_count");
    private final static QName _RoomSeetno_QNAME = new QName("", "room_seetno");
    private final static QName _CommentLock_QNAME = new QName("", "comment_lock");
    private final static QName _OpenTime_QNAME = new QName("", "open_time");
    private final static QName _IsNsStream_QNAME = new QName("", "is_ns_stream");
    private final static QName _TwitterTag_QNAME = new QName("", "twitter_tag");
    private final static QName _FooterComment_QNAME = new QName("", "footer_comment");
    private final static QName _Ticket_QNAME = new QName("", "ticket");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _Thread_QNAME = new QName("", "thread");
    private final static QName _FullVideo_QNAME = new QName("", "full_video");
    private final static QName _IsNoticeViewerBalloonEnabled_QNAME = new QName("", "is_notice_viewer_balloon_enabled");
    private final static QName _DisplayLines_QNAME = new QName("", "display_lines");
    private final static QName _ProviderType_QNAME = new QName("", "provider_type");
    private final static QName _AfterAuth_QNAME = new QName("", "after_auth");
    private final static QName _PictureUrl_QNAME = new QName("", "picture_url");
    private final static QName _Status_QNAME = new QName("", "status");
    private final static QName _RoomLabel_QNAME = new QName("", "room_label");
    private final static QName _Nickname_QNAME = new QName("", "nickname");
    private final static QName _AllowNetduetto_QNAME = new QName("", "allow_netduetto");
    private final static QName _International_QNAME = new QName("", "international");
    private final static QName _InfinityMode_QNAME = new QName("", "infinity_mode");
    private final static QName _Url_QNAME = new QName("", "url");
    private final static QName _TweetToken_QNAME = new QName("", "tweet_token");
    private final static QName _EndTime_QNAME = new QName("", "end_time");
    private final static QName _QosAnalytics_QNAME = new QName("", "qos_analytics");
    private final static QName _IsNonarchiveTimeshiftEnabled_QNAME = new QName("", "is_nonarchive_timeshift_enabled");
    private final static QName _IsPremium_QNAME = new QName("", "is_premium");
    private final static QName _ProfileImageUrl_QNAME = new QName("", "profile_image_url");
    private final static QName _DanjoCommentMode_QNAME = new QName("", "danjo_comment_mode");
    private final static QName _Port_QNAME = new QName("", "port");
    private final static QName _GameTime_QNAME = new QName("", "game_time");
    private final static QName _ErrorReport_QNAME = new QName("", "error_report");
    private final static QName _Oidashi_QNAME = new QName("", "oidashi");
    private final static QName _UserDomain_QNAME = new QName("", "userDomain");
    private final static QName _UserLanguage_QNAME = new QName("", "userLanguage");
    private final static QName _ThumbUrl_QNAME = new QName("", "thumb_url");
    private final static QName _Nstype_QNAME = new QName("", "nstype");
    private final static QName _NdToken_QNAME = new QName("", "nd_token");
    private final static QName _Id_QNAME = new QName("", "id");
    private final static QName _Title_QNAME = new QName("", "title");
    private final static QName _LiveApiUrl_QNAME = new QName("", "live_api_url");
    private final static QName _KickoutVideo_QNAME = new QName("", "kickout_video");
    private final static QName _ForceNicowariOff_QNAME = new QName("", "force_nicowari_off");
    private final static QName _BackgroundComment_QNAME = new QName("", "background_comment");
    private final static QName _UserId_QNAME = new QName("", "user_id");
    private final static QName _FollowersCount_QNAME = new QName("", "followers_count");
    private final static QName _SplitBottom_QNAME = new QName("", "split_bottom");
    private final static QName _CommentCount_QNAME = new QName("", "comment_count");
    private final static QName _WatchCount_QNAME = new QName("", "watch_count");
    private final static QName _IsArchiveplayserver_QNAME = new QName("", "is_archiveplayserver");
    private final static QName _Nspanel_QNAME = new QName("", "nspanel");
    private final static QName _IsRerunStream_QNAME = new QName("", "is_rerun_stream");
    private final static QName _IsReserved_QNAME = new QName("", "is_reserved");
    private final static QName _HeaderComment_QNAME = new QName("", "header_comment");
    private final static QName _SplitTop_QNAME = new QName("", "split_top");
    private final static QName _IsOwner_QNAME = new QName("", "is_owner");
    private final static QName _LiveEnabled_QNAME = new QName("", "live_enabled");
    private final static QName _OwnerId_QNAME = new QName("", "owner_id");
    private final static QName _UserSex_QNAME = new QName("", "userSex");
    private final static QName _StartTime_QNAME = new QName("", "start_time");
    private final static QName _IsTimeshiftReserved_QNAME = new QName("", "is_timeshift_reserved");
    private final static QName _ScreenName_QNAME = new QName("", "screen_name");
    private final static QName _Archive_QNAME = new QName("", "archive");
    private final static QName _BaseTime_QNAME = new QName("", "base_time");
    private final static QName _UserAge_QNAME = new QName("", "userAge");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ns }
     * 
     */
    public Ns createNs() {
        return new Ns();
    }

    /**
     * Create an instance of {@link Getplayerstatus }
     * 
     */
    public Getplayerstatus createGetplayerstatus() {
        return new Getplayerstatus();
    }

    /**
     * Create an instance of {@link Stream }
     * 
     */
    public Stream createStream() {
        return new Stream();
    }

    /**
     * Create an instance of {@link DefaultCommunity }
     * 
     */
    public DefaultCommunity createDefaultCommunity() {
        return new DefaultCommunity();
    }

    /**
     * Create an instance of {@link OwnerName }
     * 
     */
    public OwnerName createOwnerName() {
        return new OwnerName();
    }

    /**
     * Create an instance of {@link AfterVideo }
     * 
     */
    public AfterVideo createAfterVideo() {
        return new AfterVideo();
    }

    /**
     * Create an instance of {@link BeforeVideo }
     * 
     */
    public BeforeVideo createBeforeVideo() {
        return new BeforeVideo();
    }

    /**
     * Create an instance of {@link Press }
     * 
     */
    public Press createPress() {
        return new Press();
    }

    /**
     * Create an instance of {@link StyleConf }
     * 
     */
    public StyleConf createStyleConf() {
        return new StyleConf();
    }

    /**
     * Create an instance of {@link PluginDelay }
     * 
     */
    public PluginDelay createPluginDelay() {
        return new PluginDelay();
    }

    /**
     * Create an instance of {@link PluginUrl }
     * 
     */
    public PluginUrl createPluginUrl() {
        return new PluginUrl();
    }

    /**
     * Create an instance of {@link PluginUrls }
     * 
     */
    public PluginUrls createPluginUrls() {
        return new PluginUrls();
    }

    /**
     * Create an instance of {@link FontScale }
     * 
     */
    public FontScale createFontScale() {
        return new FontScale();
    }

    /**
     * Create an instance of {@link Telop }
     * 
     */
    public Telop createTelop() {
        return new Telop();
    }

    /**
     * Create an instance of {@link ContentsList }
     * 
     */
    public ContentsList createContentsList() {
        return new ContentsList();
    }

    /**
     * Create an instance of {@link Contents }
     * 
     */
    public Contents createContents() {
        return new Contents();
    }

    /**
     * Create an instance of {@link IsPriorityPrefecture }
     * 
     */
    public IsPriorityPrefecture createIsPriorityPrefecture() {
        return new IsPriorityPrefecture();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link TwitterInfo }
     * 
     */
    public TwitterInfo createTwitterInfo() {
        return new TwitterInfo();
    }

    /**
     * Create an instance of {@link Rtmp }
     * 
     */
    public Rtmp createRtmp() {
        return new Rtmp();
    }

    /**
     * Create an instance of {@link Ms }
     * 
     */
    public Ms createMs() {
        return new Ms();
    }

    /**
     * Create an instance of {@link TidList }
     * 
     */
    public TidList createTidList() {
        return new TidList();
    }

    /**
     * Create an instance of {@link Twitter }
     * 
     */
    public Twitter createTwitter() {
        return new Twitter();
    }

    /**
     * Create an instance of {@link Player }
     * 
     */
    public Player createPlayer() {
        return new Player();
    }

    /**
     * Create an instance of {@link DialogImage }
     * 
     */
    public DialogImage createDialogImage() {
        return new DialogImage();
    }

    /**
     * Create an instance of {@link Marquee }
     * 
     */
    public Marquee createMarquee() {
        return new Marquee();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ng_scoring")
    public JAXBElement<BigInteger> createNgScoring(BigInteger value) {
        return new JAXBElement<BigInteger>(_NgScoring_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userPrefecture")
    public JAXBElement<BigInteger> createUserPrefecture(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserPrefecture_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bourbon_url")
    public JAXBElement<String> createBourbonUrl(String value) {
        return new JAXBElement<String>(_BourbonUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_vip")
    public JAXBElement<BigInteger> createIsVip(BigInteger value) {
        return new JAXBElement<BigInteger>(_IsVip_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "display_time")
    public JAXBElement<BigInteger> createDisplayTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_DisplayTime_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "enable")
    public JAXBElement<BigInteger> createEnable(BigInteger value) {
        return new JAXBElement<BigInteger>(_Enable_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "game_key")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGameKey(String value) {
        return new JAXBElement<String>(_GameKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addr")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAddr(String value) {
        return new JAXBElement<String>(_Addr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vip_mode_count")
    public JAXBElement<BigInteger> createVipModeCount(BigInteger value) {
        return new JAXBElement<BigInteger>(_VipModeCount_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "room_seetno")
    public JAXBElement<BigInteger> createRoomSeetno(BigInteger value) {
        return new JAXBElement<BigInteger>(_RoomSeetno_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "comment_lock")
    public JAXBElement<BigInteger> createCommentLock(BigInteger value) {
        return new JAXBElement<BigInteger>(_CommentLock_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "open_time")
    public JAXBElement<BigInteger> createOpenTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_OpenTime_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_ns_stream")
    public JAXBElement<BigInteger> createIsNsStream(BigInteger value) {
        return new JAXBElement<BigInteger>(_IsNsStream_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "twitter_tag")
    public JAXBElement<String> createTwitterTag(String value) {
        return new JAXBElement<String>(_TwitterTag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "footer_comment")
    public JAXBElement<BigInteger> createFooterComment(BigInteger value) {
        return new JAXBElement<BigInteger>(_FooterComment_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ticket")
    public JAXBElement<String> createTicket(String value) {
        return new JAXBElement<String>(_Ticket_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "thread")
    public JAXBElement<BigInteger> createThread(BigInteger value) {
        return new JAXBElement<BigInteger>(_Thread_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "full_video")
    public JAXBElement<String> createFullVideo(String value) {
        return new JAXBElement<String>(_FullVideo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_notice_viewer_balloon_enabled")
    public JAXBElement<BigInteger> createIsNoticeViewerBalloonEnabled(BigInteger value) {
        return new JAXBElement<BigInteger>(_IsNoticeViewerBalloonEnabled_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "display_lines")
    public JAXBElement<BigInteger> createDisplayLines(BigInteger value) {
        return new JAXBElement<BigInteger>(_DisplayLines_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "provider_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProviderType(String value) {
        return new JAXBElement<String>(_ProviderType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "after_auth")
    public JAXBElement<BigInteger> createAfterAuth(BigInteger value) {
        return new JAXBElement<BigInteger>(_AfterAuth_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "picture_url")
    public JAXBElement<String> createPictureUrl(String value) {
        return new JAXBElement<String>(_PictureUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "room_label")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRoomLabel(String value) {
        return new JAXBElement<String>(_RoomLabel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nickname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNickname(String value) {
        return new JAXBElement<String>(_Nickname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "allow_netduetto")
    public JAXBElement<BigInteger> createAllowNetduetto(BigInteger value) {
        return new JAXBElement<BigInteger>(_AllowNetduetto_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "international")
    public JAXBElement<BigInteger> createInternational(BigInteger value) {
        return new JAXBElement<BigInteger>(_International_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "infinity_mode")
    public JAXBElement<BigInteger> createInfinityMode(BigInteger value) {
        return new JAXBElement<BigInteger>(_InfinityMode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "url")
    public JAXBElement<String> createUrl(String value) {
        return new JAXBElement<String>(_Url_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tweet_token")
    public JAXBElement<String> createTweetToken(String value) {
        return new JAXBElement<String>(_TweetToken_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "end_time")
    public JAXBElement<BigInteger> createEndTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_EndTime_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "qos_analytics")
    public JAXBElement<BigInteger> createQosAnalytics(BigInteger value) {
        return new JAXBElement<BigInteger>(_QosAnalytics_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_nonarchive_timeshift_enabled")
    public JAXBElement<BigInteger> createIsNonarchiveTimeshiftEnabled(BigInteger value) {
        return new JAXBElement<BigInteger>(_IsNonarchiveTimeshiftEnabled_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_premium")
    public JAXBElement<BigInteger> createIsPremium(BigInteger value) {
        return new JAXBElement<BigInteger>(_IsPremium_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "profile_image_url")
    public JAXBElement<String> createProfileImageUrl(String value) {
        return new JAXBElement<String>(_ProfileImageUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "danjo_comment_mode")
    public JAXBElement<BigInteger> createDanjoCommentMode(BigInteger value) {
        return new JAXBElement<BigInteger>(_DanjoCommentMode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "port")
    public JAXBElement<BigInteger> createPort(BigInteger value) {
        return new JAXBElement<BigInteger>(_Port_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "game_time")
    public JAXBElement<BigInteger> createGameTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_GameTime_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "error_report")
    public JAXBElement<BigInteger> createErrorReport(BigInteger value) {
        return new JAXBElement<BigInteger>(_ErrorReport_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "oidashi")
    public JAXBElement<String> createOidashi(String value) {
        return new JAXBElement<String>(_Oidashi_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userDomain")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUserDomain(String value) {
        return new JAXBElement<String>(_UserDomain_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userLanguage")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUserLanguage(String value) {
        return new JAXBElement<String>(_UserLanguage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "thumb_url")
    public JAXBElement<String> createThumbUrl(String value) {
        return new JAXBElement<String>(_ThumbUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nstype")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNstype(String value) {
        return new JAXBElement<String>(_Nstype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nd_token")
    public JAXBElement<String> createNdToken(String value) {
        return new JAXBElement<String>(_NdToken_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "live_api_url")
    public JAXBElement<String> createLiveApiUrl(String value) {
        return new JAXBElement<String>(_LiveApiUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kickout_video")
    public JAXBElement<String> createKickoutVideo(String value) {
        return new JAXBElement<String>(_KickoutVideo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "force_nicowari_off")
    public JAXBElement<BigInteger> createForceNicowariOff(BigInteger value) {
        return new JAXBElement<BigInteger>(_ForceNicowariOff_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "background_comment")
    public JAXBElement<BigInteger> createBackgroundComment(BigInteger value) {
        return new JAXBElement<BigInteger>(_BackgroundComment_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_id")
    public JAXBElement<BigInteger> createUserId(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "followers_count")
    public JAXBElement<BigInteger> createFollowersCount(BigInteger value) {
        return new JAXBElement<BigInteger>(_FollowersCount_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "split_bottom")
    public JAXBElement<BigInteger> createSplitBottom(BigInteger value) {
        return new JAXBElement<BigInteger>(_SplitBottom_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "comment_count")
    public JAXBElement<BigInteger> createCommentCount(BigInteger value) {
        return new JAXBElement<BigInteger>(_CommentCount_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "watch_count")
    public JAXBElement<BigInteger> createWatchCount(BigInteger value) {
        return new JAXBElement<BigInteger>(_WatchCount_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_archiveplayserver")
    public JAXBElement<BigInteger> createIsArchiveplayserver(BigInteger value) {
        return new JAXBElement<BigInteger>(_IsArchiveplayserver_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nspanel")
    public JAXBElement<String> createNspanel(String value) {
        return new JAXBElement<String>(_Nspanel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_rerun_stream")
    public JAXBElement<BigInteger> createIsRerunStream(BigInteger value) {
        return new JAXBElement<BigInteger>(_IsRerunStream_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_reserved")
    public JAXBElement<BigInteger> createIsReserved(BigInteger value) {
        return new JAXBElement<BigInteger>(_IsReserved_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "header_comment")
    public JAXBElement<BigInteger> createHeaderComment(BigInteger value) {
        return new JAXBElement<BigInteger>(_HeaderComment_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "split_top")
    public JAXBElement<BigInteger> createSplitTop(BigInteger value) {
        return new JAXBElement<BigInteger>(_SplitTop_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_owner")
    public JAXBElement<BigInteger> createIsOwner(BigInteger value) {
        return new JAXBElement<BigInteger>(_IsOwner_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "live_enabled")
    public JAXBElement<BigInteger> createLiveEnabled(BigInteger value) {
        return new JAXBElement<BigInteger>(_LiveEnabled_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "owner_id")
    public JAXBElement<BigInteger> createOwnerId(BigInteger value) {
        return new JAXBElement<BigInteger>(_OwnerId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userSex")
    public JAXBElement<BigInteger> createUserSex(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserSex_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "start_time")
    public JAXBElement<BigInteger> createStartTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_StartTime_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "is_timeshift_reserved")
    public JAXBElement<BigInteger> createIsTimeshiftReserved(BigInteger value) {
        return new JAXBElement<BigInteger>(_IsTimeshiftReserved_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "screen_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createScreenName(String value) {
        return new JAXBElement<String>(_ScreenName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "archive")
    public JAXBElement<BigInteger> createArchive(BigInteger value) {
        return new JAXBElement<BigInteger>(_Archive_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "base_time")
    public JAXBElement<BigInteger> createBaseTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_BaseTime_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userAge")
    public JAXBElement<BigInteger> createUserAge(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserAge_QNAME, BigInteger.class, null, value);
    }

}
