//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.18 at 05:23:45 PM JST 
//


package net.tiger.star.nsen.jaxb;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}qos_analytics"/>
 *         &lt;element ref="{}dialog_image"/>
 *         &lt;element ref="{}is_notice_viewer_balloon_enabled"/>
 *         &lt;element ref="{}error_report"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "qosAnalytics",
    "dialogImage",
    "isNoticeViewerBalloonEnabled",
    "errorReport"
})
@XmlRootElement(name = "player")
public class Player {

    @XmlElement(name = "qos_analytics", required = true)
    protected BigInteger qosAnalytics;
    @XmlElement(name = "dialog_image", required = true)
    protected DialogImage dialogImage;
    @XmlElement(name = "is_notice_viewer_balloon_enabled", required = true)
    protected BigInteger isNoticeViewerBalloonEnabled;
    @XmlElement(name = "error_report", required = true)
    protected BigInteger errorReport;

    /**
     * Gets the value of the qosAnalytics property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQosAnalytics() {
        return qosAnalytics;
    }

    /**
     * Sets the value of the qosAnalytics property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQosAnalytics(BigInteger value) {
        this.qosAnalytics = value;
    }

    /**
     * Gets the value of the dialogImage property.
     * 
     * @return
     *     possible object is
     *     {@link DialogImage }
     *     
     */
    public DialogImage getDialogImage() {
        return dialogImage;
    }

    /**
     * Sets the value of the dialogImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link DialogImage }
     *     
     */
    public void setDialogImage(DialogImage value) {
        this.dialogImage = value;
    }

    /**
     * Gets the value of the isNoticeViewerBalloonEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIsNoticeViewerBalloonEnabled() {
        return isNoticeViewerBalloonEnabled;
    }

    /**
     * Sets the value of the isNoticeViewerBalloonEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIsNoticeViewerBalloonEnabled(BigInteger value) {
        this.isNoticeViewerBalloonEnabled = value;
    }

    /**
     * Gets the value of the errorReport property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getErrorReport() {
        return errorReport;
    }

    /**
     * Sets the value of the errorReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setErrorReport(BigInteger value) {
        this.errorReport = value;
    }

}
