//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.18 at 05:23:45 PM JST 
//


package net.tiger.star.nsen.jaxb;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}display_lines"/>
 *         &lt;element ref="{}display_time"/>
 *         &lt;element ref="{}style_conf"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "displayLines",
    "displayTime",
    "styleConf"
})
@XmlRootElement(name = "press")
public class Press {

    @XmlElement(name = "display_lines", required = true)
    protected BigInteger displayLines;
    @XmlElement(name = "display_time", required = true)
    protected BigInteger displayTime;
    @XmlElement(name = "style_conf", required = true)
    protected StyleConf styleConf;

    /**
     * Gets the value of the displayLines property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDisplayLines() {
        return displayLines;
    }

    /**
     * Sets the value of the displayLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDisplayLines(BigInteger value) {
        this.displayLines = value;
    }

    /**
     * Gets the value of the displayTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDisplayTime() {
        return displayTime;
    }

    /**
     * Sets the value of the displayTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDisplayTime(BigInteger value) {
        this.displayTime = value;
    }

    /**
     * Gets the value of the styleConf property.
     * 
     * @return
     *     possible object is
     *     {@link StyleConf }
     *     
     */
    public StyleConf getStyleConf() {
        return styleConf;
    }

    /**
     * Sets the value of the styleConf property.
     * 
     * @param value
     *     allowed object is
     *     {@link StyleConf }
     *     
     */
    public void setStyleConf(StyleConf value) {
        this.styleConf = value;
    }

}
