//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.18 at 05:23:45 PM JST 
//


package net.tiger.star.nsen.jaxb;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}id"/>
 *         &lt;element ref="{}title"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}provider_type"/>
 *         &lt;element ref="{}default_community"/>
 *         &lt;element ref="{}international"/>
 *         &lt;element ref="{}is_owner"/>
 *         &lt;element ref="{}owner_id"/>
 *         &lt;element ref="{}owner_name"/>
 *         &lt;element ref="{}is_reserved"/>
 *         &lt;element ref="{}watch_count"/>
 *         &lt;element ref="{}comment_count"/>
 *         &lt;element ref="{}base_time"/>
 *         &lt;element ref="{}open_time"/>
 *         &lt;element ref="{}start_time"/>
 *         &lt;element ref="{}end_time"/>
 *         &lt;element ref="{}is_rerun_stream"/>
 *         &lt;element ref="{}is_archiveplayserver"/>
 *         &lt;element ref="{}bourbon_url"/>
 *         &lt;element ref="{}full_video"/>
 *         &lt;element ref="{}after_video"/>
 *         &lt;element ref="{}before_video"/>
 *         &lt;element ref="{}kickout_video"/>
 *         &lt;element ref="{}twitter_tag"/>
 *         &lt;element ref="{}danjo_comment_mode"/>
 *         &lt;element ref="{}infinity_mode"/>
 *         &lt;element ref="{}archive"/>
 *         &lt;element ref="{}press"/>
 *         &lt;element ref="{}plugin_delay"/>
 *         &lt;element ref="{}plugin_url"/>
 *         &lt;element ref="{}plugin_urls"/>
 *         &lt;element ref="{}allow_netduetto"/>
 *         &lt;element ref="{}nd_token"/>
 *         &lt;element ref="{}ng_scoring"/>
 *         &lt;element ref="{}is_nonarchive_timeshift_enabled"/>
 *         &lt;element ref="{}is_timeshift_reserved"/>
 *         &lt;element ref="{}header_comment"/>
 *         &lt;element ref="{}footer_comment"/>
 *         &lt;element ref="{}split_bottom"/>
 *         &lt;element ref="{}split_top"/>
 *         &lt;element ref="{}background_comment"/>
 *         &lt;element ref="{}font_scale"/>
 *         &lt;element ref="{}comment_lock"/>
 *         &lt;element ref="{}telop"/>
 *         &lt;element ref="{}contents_list"/>
 *         &lt;element ref="{}picture_url"/>
 *         &lt;element ref="{}thumb_url"/>
 *         &lt;element ref="{}is_priority_prefecture"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "title",
    "description",
    "providerType",
    "defaultCommunity",
    "international",
    "isOwner",
    "ownerId",
    "ownerName",
    "isReserved",
    "watchCount",
    "commentCount",
    "baseTime",
    "openTime",
    "startTime",
    "endTime",
    "isRerunStream",
    "isArchiveplayserver",
    "bourbonUrl",
    "fullVideo",
    "afterVideo",
    "beforeVideo",
    "kickoutVideo",
    "twitterTag",
    "danjoCommentMode",
    "infinityMode",
    "archive",
    "press",
    "pluginDelay",
    "pluginUrl",
    "pluginUrls",
    "allowNetduetto",
    "ndToken",
    "ngScoring",
    "isNonarchiveTimeshiftEnabled",
    "isTimeshiftReserved",
    "headerComment",
    "footerComment",
    "splitBottom",
    "splitTop",
    "backgroundComment",
    "fontScale",
    "commentLock",
    "telop",
    "contentsList",
    "pictureUrl",
    "thumbUrl",
    "isPriorityPrefecture"
})
@XmlRootElement(name = "stream")
public class Stream {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String id;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(name = "provider_type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String providerType;
    @XmlElement(name = "default_community", required = true)
    protected DefaultCommunity defaultCommunity;
    @XmlElement(required = true)
    protected BigInteger international;
    @XmlElement(name = "is_owner", required = true)
    protected BigInteger isOwner;
    @XmlElement(name = "owner_id", required = true)
    protected BigInteger ownerId;
    @XmlElement(name = "owner_name", required = true)
    protected OwnerName ownerName;
    @XmlElement(name = "is_reserved", required = true)
    protected BigInteger isReserved;
    @XmlElement(name = "watch_count", required = true)
    protected BigInteger watchCount;
    @XmlElement(name = "comment_count", required = true)
    protected BigInteger commentCount;
    @XmlElement(name = "base_time", required = true)
    protected BigInteger baseTime;
    @XmlElement(name = "open_time", required = true)
    protected BigInteger openTime;
    @XmlElement(name = "start_time", required = true)
    protected BigInteger startTime;
    @XmlElement(name = "end_time", required = true)
    protected BigInteger endTime;
    @XmlElement(name = "is_rerun_stream", required = true)
    protected BigInteger isRerunStream;
    @XmlElement(name = "is_archiveplayserver", required = true)
    protected BigInteger isArchiveplayserver;
    @XmlElement(name = "bourbon_url", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String bourbonUrl;
    @XmlElement(name = "full_video", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String fullVideo;
    @XmlElement(name = "after_video", required = true)
    protected AfterVideo afterVideo;
    @XmlElement(name = "before_video", required = true)
    protected BeforeVideo beforeVideo;
    @XmlElement(name = "kickout_video", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String kickoutVideo;
    @XmlElement(name = "twitter_tag", required = true)
    protected String twitterTag;
    @XmlElement(name = "danjo_comment_mode", required = true)
    protected BigInteger danjoCommentMode;
    @XmlElement(name = "infinity_mode", required = true)
    protected BigInteger infinityMode;
    @XmlElement(required = true)
    protected BigInteger archive;
    @XmlElement(required = true)
    protected Press press;
    @XmlElement(name = "plugin_delay", required = true)
    protected PluginDelay pluginDelay;
    @XmlElement(name = "plugin_url", required = true)
    protected PluginUrl pluginUrl;
    @XmlElement(name = "plugin_urls", required = true)
    protected PluginUrls pluginUrls;
    @XmlElement(name = "allow_netduetto", required = true)
    protected BigInteger allowNetduetto;
    @XmlElement(name = "nd_token", required = true)
    protected String ndToken;
    @XmlElement(name = "ng_scoring", required = true)
    protected BigInteger ngScoring;
    @XmlElement(name = "is_nonarchive_timeshift_enabled", required = true)
    protected BigInteger isNonarchiveTimeshiftEnabled;
    @XmlElement(name = "is_timeshift_reserved", required = true)
    protected BigInteger isTimeshiftReserved;
    @XmlElement(name = "header_comment", required = true)
    protected BigInteger headerComment;
    @XmlElement(name = "footer_comment", required = true)
    protected BigInteger footerComment;
    @XmlElement(name = "split_bottom", required = true)
    protected BigInteger splitBottom;
    @XmlElement(name = "split_top", required = true)
    protected BigInteger splitTop;
    @XmlElement(name = "background_comment", required = true)
    protected BigInteger backgroundComment;
    @XmlElement(name = "font_scale", required = true)
    protected FontScale fontScale;
    @XmlElement(name = "comment_lock", required = true)
    protected BigInteger commentLock;
    @XmlElement(required = true)
    protected Telop telop;
    @XmlElement(name = "contents_list", required = true)
    protected ContentsList contentsList;
    @XmlElement(name = "picture_url", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String pictureUrl;
    @XmlElement(name = "thumb_url", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String thumbUrl;
    @XmlElement(name = "is_priority_prefecture", required = true)
    protected IsPriorityPrefecture isPriorityPrefecture;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the providerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderType() {
        return providerType;
    }

    /**
     * Sets the value of the providerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderType(String value) {
        this.providerType = value;
    }

    /**
     * Gets the value of the defaultCommunity property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultCommunity }
     *     
     */
    public DefaultCommunity getDefaultCommunity() {
        return defaultCommunity;
    }

    /**
     * Sets the value of the defaultCommunity property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultCommunity }
     *     
     */
    public void setDefaultCommunity(DefaultCommunity value) {
        this.defaultCommunity = value;
    }

    /**
     * Gets the value of the international property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInternational() {
        return international;
    }

    /**
     * Sets the value of the international property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInternational(BigInteger value) {
        this.international = value;
    }

    /**
     * Gets the value of the isOwner property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIsOwner() {
        return isOwner;
    }

    /**
     * Sets the value of the isOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIsOwner(BigInteger value) {
        this.isOwner = value;
    }

    /**
     * Gets the value of the ownerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOwnerId() {
        return ownerId;
    }

    /**
     * Sets the value of the ownerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOwnerId(BigInteger value) {
        this.ownerId = value;
    }

    /**
     * Gets the value of the ownerName property.
     * 
     * @return
     *     possible object is
     *     {@link OwnerName }
     *     
     */
    public OwnerName getOwnerName() {
        return ownerName;
    }

    /**
     * Sets the value of the ownerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnerName }
     *     
     */
    public void setOwnerName(OwnerName value) {
        this.ownerName = value;
    }

    /**
     * Gets the value of the isReserved property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIsReserved() {
        return isReserved;
    }

    /**
     * Sets the value of the isReserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIsReserved(BigInteger value) {
        this.isReserved = value;
    }

    /**
     * Gets the value of the watchCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWatchCount() {
        return watchCount;
    }

    /**
     * Sets the value of the watchCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWatchCount(BigInteger value) {
        this.watchCount = value;
    }

    /**
     * Gets the value of the commentCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCommentCount() {
        return commentCount;
    }

    /**
     * Sets the value of the commentCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCommentCount(BigInteger value) {
        this.commentCount = value;
    }

    /**
     * Gets the value of the baseTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBaseTime() {
        return baseTime;
    }

    /**
     * Sets the value of the baseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBaseTime(BigInteger value) {
        this.baseTime = value;
    }

    /**
     * Gets the value of the openTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOpenTime() {
        return openTime;
    }

    /**
     * Sets the value of the openTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOpenTime(BigInteger value) {
        this.openTime = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStartTime(BigInteger value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEndTime(BigInteger value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the isRerunStream property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIsRerunStream() {
        return isRerunStream;
    }

    /**
     * Sets the value of the isRerunStream property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIsRerunStream(BigInteger value) {
        this.isRerunStream = value;
    }

    /**
     * Gets the value of the isArchiveplayserver property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIsArchiveplayserver() {
        return isArchiveplayserver;
    }

    /**
     * Sets the value of the isArchiveplayserver property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIsArchiveplayserver(BigInteger value) {
        this.isArchiveplayserver = value;
    }

    /**
     * Gets the value of the bourbonUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBourbonUrl() {
        return bourbonUrl;
    }

    /**
     * Sets the value of the bourbonUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBourbonUrl(String value) {
        this.bourbonUrl = value;
    }

    /**
     * Gets the value of the fullVideo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullVideo() {
        return fullVideo;
    }

    /**
     * Sets the value of the fullVideo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullVideo(String value) {
        this.fullVideo = value;
    }

    /**
     * Gets the value of the afterVideo property.
     * 
     * @return
     *     possible object is
     *     {@link AfterVideo }
     *     
     */
    public AfterVideo getAfterVideo() {
        return afterVideo;
    }

    /**
     * Sets the value of the afterVideo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AfterVideo }
     *     
     */
    public void setAfterVideo(AfterVideo value) {
        this.afterVideo = value;
    }

    /**
     * Gets the value of the beforeVideo property.
     * 
     * @return
     *     possible object is
     *     {@link BeforeVideo }
     *     
     */
    public BeforeVideo getBeforeVideo() {
        return beforeVideo;
    }

    /**
     * Sets the value of the beforeVideo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeforeVideo }
     *     
     */
    public void setBeforeVideo(BeforeVideo value) {
        this.beforeVideo = value;
    }

    /**
     * Gets the value of the kickoutVideo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKickoutVideo() {
        return kickoutVideo;
    }

    /**
     * Sets the value of the kickoutVideo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKickoutVideo(String value) {
        this.kickoutVideo = value;
    }

    /**
     * Gets the value of the twitterTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTwitterTag() {
        return twitterTag;
    }

    /**
     * Sets the value of the twitterTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTwitterTag(String value) {
        this.twitterTag = value;
    }

    /**
     * Gets the value of the danjoCommentMode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDanjoCommentMode() {
        return danjoCommentMode;
    }

    /**
     * Sets the value of the danjoCommentMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDanjoCommentMode(BigInteger value) {
        this.danjoCommentMode = value;
    }

    /**
     * Gets the value of the infinityMode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInfinityMode() {
        return infinityMode;
    }

    /**
     * Sets the value of the infinityMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInfinityMode(BigInteger value) {
        this.infinityMode = value;
    }

    /**
     * Gets the value of the archive property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getArchive() {
        return archive;
    }

    /**
     * Sets the value of the archive property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setArchive(BigInteger value) {
        this.archive = value;
    }

    /**
     * Gets the value of the press property.
     * 
     * @return
     *     possible object is
     *     {@link Press }
     *     
     */
    public Press getPress() {
        return press;
    }

    /**
     * Sets the value of the press property.
     * 
     * @param value
     *     allowed object is
     *     {@link Press }
     *     
     */
    public void setPress(Press value) {
        this.press = value;
    }

    /**
     * Gets the value of the pluginDelay property.
     * 
     * @return
     *     possible object is
     *     {@link PluginDelay }
     *     
     */
    public PluginDelay getPluginDelay() {
        return pluginDelay;
    }

    /**
     * Sets the value of the pluginDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link PluginDelay }
     *     
     */
    public void setPluginDelay(PluginDelay value) {
        this.pluginDelay = value;
    }

    /**
     * Gets the value of the pluginUrl property.
     * 
     * @return
     *     possible object is
     *     {@link PluginUrl }
     *     
     */
    public PluginUrl getPluginUrl() {
        return pluginUrl;
    }

    /**
     * Sets the value of the pluginUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link PluginUrl }
     *     
     */
    public void setPluginUrl(PluginUrl value) {
        this.pluginUrl = value;
    }

    /**
     * Gets the value of the pluginUrls property.
     * 
     * @return
     *     possible object is
     *     {@link PluginUrls }
     *     
     */
    public PluginUrls getPluginUrls() {
        return pluginUrls;
    }

    /**
     * Sets the value of the pluginUrls property.
     * 
     * @param value
     *     allowed object is
     *     {@link PluginUrls }
     *     
     */
    public void setPluginUrls(PluginUrls value) {
        this.pluginUrls = value;
    }

    /**
     * Gets the value of the allowNetduetto property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAllowNetduetto() {
        return allowNetduetto;
    }

    /**
     * Sets the value of the allowNetduetto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAllowNetduetto(BigInteger value) {
        this.allowNetduetto = value;
    }

    /**
     * Gets the value of the ndToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNdToken() {
        return ndToken;
    }

    /**
     * Sets the value of the ndToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNdToken(String value) {
        this.ndToken = value;
    }

    /**
     * Gets the value of the ngScoring property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNgScoring() {
        return ngScoring;
    }

    /**
     * Sets the value of the ngScoring property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNgScoring(BigInteger value) {
        this.ngScoring = value;
    }

    /**
     * Gets the value of the isNonarchiveTimeshiftEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIsNonarchiveTimeshiftEnabled() {
        return isNonarchiveTimeshiftEnabled;
    }

    /**
     * Sets the value of the isNonarchiveTimeshiftEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIsNonarchiveTimeshiftEnabled(BigInteger value) {
        this.isNonarchiveTimeshiftEnabled = value;
    }

    /**
     * Gets the value of the isTimeshiftReserved property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIsTimeshiftReserved() {
        return isTimeshiftReserved;
    }

    /**
     * Sets the value of the isTimeshiftReserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIsTimeshiftReserved(BigInteger value) {
        this.isTimeshiftReserved = value;
    }

    /**
     * Gets the value of the headerComment property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHeaderComment() {
        return headerComment;
    }

    /**
     * Sets the value of the headerComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHeaderComment(BigInteger value) {
        this.headerComment = value;
    }

    /**
     * Gets the value of the footerComment property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFooterComment() {
        return footerComment;
    }

    /**
     * Sets the value of the footerComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFooterComment(BigInteger value) {
        this.footerComment = value;
    }

    /**
     * Gets the value of the splitBottom property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSplitBottom() {
        return splitBottom;
    }

    /**
     * Sets the value of the splitBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSplitBottom(BigInteger value) {
        this.splitBottom = value;
    }

    /**
     * Gets the value of the splitTop property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSplitTop() {
        return splitTop;
    }

    /**
     * Sets the value of the splitTop property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSplitTop(BigInteger value) {
        this.splitTop = value;
    }

    /**
     * Gets the value of the backgroundComment property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBackgroundComment() {
        return backgroundComment;
    }

    /**
     * Sets the value of the backgroundComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBackgroundComment(BigInteger value) {
        this.backgroundComment = value;
    }

    /**
     * Gets the value of the fontScale property.
     * 
     * @return
     *     possible object is
     *     {@link FontScale }
     *     
     */
    public FontScale getFontScale() {
        return fontScale;
    }

    /**
     * Sets the value of the fontScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link FontScale }
     *     
     */
    public void setFontScale(FontScale value) {
        this.fontScale = value;
    }

    /**
     * Gets the value of the commentLock property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCommentLock() {
        return commentLock;
    }

    /**
     * Sets the value of the commentLock property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCommentLock(BigInteger value) {
        this.commentLock = value;
    }

    /**
     * Gets the value of the telop property.
     * 
     * @return
     *     possible object is
     *     {@link Telop }
     *     
     */
    public Telop getTelop() {
        return telop;
    }

    /**
     * Sets the value of the telop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Telop }
     *     
     */
    public void setTelop(Telop value) {
        this.telop = value;
    }

    /**
     * Gets the value of the contentsList property.
     * 
     * @return
     *     possible object is
     *     {@link ContentsList }
     *     
     */
    public ContentsList getContentsList() {
        return contentsList;
    }

    /**
     * Sets the value of the contentsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentsList }
     *     
     */
    public void setContentsList(ContentsList value) {
        this.contentsList = value;
    }

    /**
     * Gets the value of the pictureUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * Sets the value of the pictureUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPictureUrl(String value) {
        this.pictureUrl = value;
    }

    /**
     * Gets the value of the thumbUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThumbUrl() {
        return thumbUrl;
    }

    /**
     * Sets the value of the thumbUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThumbUrl(String value) {
        this.thumbUrl = value;
    }

    /**
     * Gets the value of the isPriorityPrefecture property.
     * 
     * @return
     *     possible object is
     *     {@link IsPriorityPrefecture }
     *     
     */
    public IsPriorityPrefecture getIsPriorityPrefecture() {
        return isPriorityPrefecture;
    }

    /**
     * Sets the value of the isPriorityPrefecture property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsPriorityPrefecture }
     *     
     */
    public void setIsPriorityPrefecture(IsPriorityPrefecture value) {
        this.isPriorityPrefecture = value;
    }

}
