//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.18 at 05:23:45 PM JST 
//


package net.tiger.star.nsen.jaxb;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}status"/>
 *         &lt;element ref="{}screen_name"/>
 *         &lt;element ref="{}followers_count"/>
 *         &lt;element ref="{}is_vip"/>
 *         &lt;element ref="{}profile_image_url"/>
 *         &lt;element ref="{}after_auth"/>
 *         &lt;element ref="{}tweet_token"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status",
    "screenName",
    "followersCount",
    "isVip",
    "profileImageUrl",
    "afterAuth",
    "tweetToken"
})
@XmlRootElement(name = "twitter_info")
public class TwitterInfo {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String status;
    @XmlElement(name = "screen_name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String screenName;
    @XmlElement(name = "followers_count", required = true)
    protected BigInteger followersCount;
    @XmlElement(name = "is_vip", required = true)
    protected BigInteger isVip;
    @XmlElement(name = "profile_image_url", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String profileImageUrl;
    @XmlElement(name = "after_auth", required = true)
    protected BigInteger afterAuth;
    @XmlElement(name = "tweet_token", required = true)
    protected String tweetToken;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the screenName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScreenName() {
        return screenName;
    }

    /**
     * Sets the value of the screenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScreenName(String value) {
        this.screenName = value;
    }

    /**
     * Gets the value of the followersCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFollowersCount() {
        return followersCount;
    }

    /**
     * Sets the value of the followersCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFollowersCount(BigInteger value) {
        this.followersCount = value;
    }

    /**
     * Gets the value of the isVip property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIsVip() {
        return isVip;
    }

    /**
     * Sets the value of the isVip property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIsVip(BigInteger value) {
        this.isVip = value;
    }

    /**
     * Gets the value of the profileImageUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileImageUrl() {
        return profileImageUrl;
    }

    /**
     * Sets the value of the profileImageUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileImageUrl(String value) {
        this.profileImageUrl = value;
    }

    /**
     * Gets the value of the afterAuth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAfterAuth() {
        return afterAuth;
    }

    /**
     * Sets the value of the afterAuth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAfterAuth(BigInteger value) {
        this.afterAuth = value;
    }

    /**
     * Gets the value of the tweetToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTweetToken() {
        return tweetToken;
    }

    /**
     * Sets the value of the tweetToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTweetToken(String value) {
        this.tweetToken = value;
    }

}
