//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.18 at 05:23:45 PM JST 
//


package net.tiger.star.nsen.jaxb;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}live_enabled"/>
 *         &lt;element ref="{}vip_mode_count"/>
 *         &lt;element ref="{}live_api_url"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "liveEnabled",
    "vipModeCount",
    "liveApiUrl"
})
@XmlRootElement(name = "twitter")
public class Twitter {

    @XmlElement(name = "live_enabled", required = true)
    protected BigInteger liveEnabled;
    @XmlElement(name = "vip_mode_count", required = true)
    protected BigInteger vipModeCount;
    @XmlElement(name = "live_api_url", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String liveApiUrl;

    /**
     * Gets the value of the liveEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLiveEnabled() {
        return liveEnabled;
    }

    /**
     * Sets the value of the liveEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLiveEnabled(BigInteger value) {
        this.liveEnabled = value;
    }

    /**
     * Gets the value of the vipModeCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVipModeCount() {
        return vipModeCount;
    }

    /**
     * Sets the value of the vipModeCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVipModeCount(BigInteger value) {
        this.vipModeCount = value;
    }

    /**
     * Gets the value of the liveApiUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLiveApiUrl() {
        return liveApiUrl;
    }

    /**
     * Sets the value of the liveApiUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLiveApiUrl(String value) {
        this.liveApiUrl = value;
    }

}
