//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.18 at 05:23:45 PM JST 
//


package net.tiger.star.nsen.jaxb;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}user_id"/>
 *         &lt;element ref="{}nickname"/>
 *         &lt;element ref="{}is_premium"/>
 *         &lt;element ref="{}userAge"/>
 *         &lt;element ref="{}userSex"/>
 *         &lt;element ref="{}userDomain"/>
 *         &lt;element ref="{}userPrefecture"/>
 *         &lt;element ref="{}userLanguage"/>
 *         &lt;element ref="{}room_label"/>
 *         &lt;element ref="{}room_seetno"/>
 *         &lt;element ref="{}twitter_info"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userId",
    "nickname",
    "isPremium",
    "userAge",
    "userSex",
    "userDomain",
    "userPrefecture",
    "userLanguage",
    "roomLabel",
    "roomSeetno",
    "twitterInfo"
})
@XmlRootElement(name = "user")
public class User {

    @XmlElement(name = "user_id", required = true)
    protected BigInteger userId;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String nickname;
    @XmlElement(name = "is_premium", required = true)
    protected BigInteger isPremium;
    @XmlElement(required = true)
    protected BigInteger userAge;
    @XmlElement(required = true)
    protected BigInteger userSex;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String userDomain;
    @XmlElement(required = true)
    protected BigInteger userPrefecture;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String userLanguage;
    @XmlElement(name = "room_label", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String roomLabel;
    @XmlElement(name = "room_seetno", required = true)
    protected BigInteger roomSeetno;
    @XmlElement(name = "twitter_info", required = true)
    protected TwitterInfo twitterInfo;

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUserId(BigInteger value) {
        this.userId = value;
    }

    /**
     * Gets the value of the nickname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * Sets the value of the nickname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNickname(String value) {
        this.nickname = value;
    }

    /**
     * Gets the value of the isPremium property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIsPremium() {
        return isPremium;
    }

    /**
     * Sets the value of the isPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIsPremium(BigInteger value) {
        this.isPremium = value;
    }

    /**
     * Gets the value of the userAge property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUserAge() {
        return userAge;
    }

    /**
     * Sets the value of the userAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUserAge(BigInteger value) {
        this.userAge = value;
    }

    /**
     * Gets the value of the userSex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUserSex() {
        return userSex;
    }

    /**
     * Sets the value of the userSex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUserSex(BigInteger value) {
        this.userSex = value;
    }

    /**
     * Gets the value of the userDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDomain() {
        return userDomain;
    }

    /**
     * Sets the value of the userDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDomain(String value) {
        this.userDomain = value;
    }

    /**
     * Gets the value of the userPrefecture property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUserPrefecture() {
        return userPrefecture;
    }

    /**
     * Sets the value of the userPrefecture property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUserPrefecture(BigInteger value) {
        this.userPrefecture = value;
    }

    /**
     * Gets the value of the userLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserLanguage() {
        return userLanguage;
    }

    /**
     * Sets the value of the userLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserLanguage(String value) {
        this.userLanguage = value;
    }

    /**
     * Gets the value of the roomLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomLabel() {
        return roomLabel;
    }

    /**
     * Sets the value of the roomLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomLabel(String value) {
        this.roomLabel = value;
    }

    /**
     * Gets the value of the roomSeetno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRoomSeetno() {
        return roomSeetno;
    }

    /**
     * Sets the value of the roomSeetno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRoomSeetno(BigInteger value) {
        this.roomSeetno = value;
    }

    /**
     * Gets the value of the twitterInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TwitterInfo }
     *     
     */
    public TwitterInfo getTwitterInfo() {
        return twitterInfo;
    }

    /**
     * Sets the value of the twitterInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TwitterInfo }
     *     
     */
    public void setTwitterInfo(TwitterInfo value) {
        this.twitterInfo = value;
    }

}
